branch-defaults:
  default:
    environment: null
global:
  application_name: blacklistapi-env
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2023 v3.1.7 running .NET 8
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
