version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Instalando las dependencias necesarias"
  pre_build:
    commands:
      - echo "Installing Docker..."
      - apt-get update && apt-get install -y docker.io
      - echo "Restaurando las dependencias del proyecto..."
      - dotnet restore BlackListApi/BlackListApi/BlackListApi.csproj
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 985539775509.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo "Compilando la aplicación..."
      - dotnet build BlackListApi/BlackListApi/BlackListApi.csproj --configuration Release
  post_build:
    commands:
      - echo "Ejecutando las pruebas..."
      - dotnet test BlackListApi/Tests/Tests.csproj --configuration Release
      - echo "Generando archivos de publicación..."
      - dotnet publish BlackListApi/BlackListApi/BlackListApi.csproj --configuration Release -o output/publish
      - echo "Construyendo la imagen del contenedor..."
      - echo "Generando la imagen con tag = latest"
      - docker build -t 529088270196.dkr.ecr.us-east-1.amazonaws.com/blacklistapi:latest -f BlackListApi/Dockerfile.ci .
      - echo "Pushing la imagen al repositorio ECR aws..."
      - docker push  529088270196.dkr.ecr.us-east-1.amazonaws.com/blacklistapi:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"container-blacklist","imageUri":"529088270196.dkr.ecr.us-east-1.amazonaws.com/blacklistapi:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"529088270196.dkr.ecr.us-east-1.amazonaws.com/blacklistapi:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
      
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
    - taskdef.json
    - appspec.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json


cache:
  paths:
    - '**/obj/**'
    - '**/bin/**'

